@startuml
' #ffbb00 - auth
' #00b32a - userFriends
' #0077ff - products
' #c700d9 - userProducts
' Actors declarations
actor Użytkownik as U

' UseCases declarations
' UserFriends use cases declarations
"Wyszukaj użytkowników" as (FindUsers) #00b32a
"Wyślij zaproszenie" as (SendFriendRequest) #00b32a
"Zaakcpetuj zaproszenie" as (AcceptFriendRequest) #00b32a
"Anuluj zaproszenie" as (CancelFriendRequest) #00b32a
"Odrzuć zaproszenie" as (RefuseFriendRequest) #00b32a
"Usuń znajomego" as (DeleteFriend) #00b32a
"Wyświetl listę znajomych" as (DisplayFriendsList) #00b32a

' UserFriends use cases
U -up- FindUsers

U -right- DisplayFriendsList

U -down- SendFriendRequest

CancelFriendRequest .down.> SendFriendRequest : extend
U -- CancelFriendRequest

RefuseFriendRequest .down.> SendFriendRequest : extend
U -down- RefuseFriendRequest


AcceptFriendRequest .down.> SendFriendRequest : extend
U -- AcceptFriendRequest



U -left- DeleteFriend

@enduml