@startuml
' #ffbb00 - auth
' #00b32a - userFriends
' #0077ff - products
' #c700d9 - userProducts
' Actors declarations
actor Użytkownik as U

' UseCases declarations

' Product use cases declarations
"Znajdź produkt" as (FinProduct) #0077ff
"Dodaj produkt" as (AddNewProduct) #0077ff
"Zmodyfikuj produkt" as (ModifyProduct) #0077ff
"Usuń produkt" as (DeleteProduct) #0077ff
"Wyświetl produkty użytkownika" as (DisplayUserProducts) #0077ff
"Filtruj produkty użytkownika" as (FilterUserProducts) #0077ff

' Product use casess
U -up- FinProduct
U -left- AddNewProduct
U -down- ModifyProduct
U -down- DeleteProduct
U -right- FilterUserProducts
U -right- DisplayUserProducts

@enduml