@startuml
' #ffbb00 - auth

' Actors declarations
actor Użytkownik as U

' UseCases declarations

' Auth use cases declarations
"Rejestracja" as (Registration) #ffbb00
"Logowanie" as (Login) #ffbb00
"Wylogowanie" as (Logout) #ffbb00
"Podtrzymanie sesji" as (Session) #ffbb00

' Auth use cases
U -- Registration
U -- Login
 Session .> Login: extends
U -- Logout

@enduml