@startuml
' #ffbb00 - auth
' #00b32a - userFriends
' #0077ff - products
' #c700d9 - userProducts
' Actors declarations
actor Użytkownik as U

' UserProduct use cases declarations
"Dodaj produkt do dziennika" as (AddProductToDiary) #c700d9
"Zmodyfikuj ilość" as (ModifyEntry) #c700d9
"Usuń produkt" as (DeleteEntry) #c700d9
"Wyświetl produkty po dacie" as (DisplayProductEntriesByDate) #c700d9

' UserProduct use cases
U -up- DisplayProductEntriesByDate
U -right- AddProductToDiary
U -left- ModifyEntry
U -down- DeleteEntry

@enduml